BDEPEND=>=app-editors/emacs-25.3:* >=dev-vcs/git-1.8.2.1[curl]
DEFINED_PHASES=compile configure install postinst postrm prepare setup test unpack
DEPEND=app-emacs/s
DESCRIPTION=An emacs mode for handling Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp git-r3
KEYWORDS=~amd64 ~x86
LICENSE=Apache-2.0
PROPERTIES=live
RDEPEND=>=app-editors/emacs-25.3:*
SLOT=0
_eclasses_=elisp-common	dcd21c5d379fc2217e95f529504c5fe0	elisp	7190c722d9e06fabcae26ef1e1dc9183	git-r3	27e13c09a4c7e4c78ac812f74727e676
_md5_=360d1647a57d7040f899cbff3acaff39
