BDEPEND=>=app-editors/emacs-23.1:* >=dev-vcs/git-1.8.2.1[curl]
DEFINED_PHASES=compile configure install postinst postrm prepare setup unpack
DEPEND=app-emacs/s
DESCRIPTION=An emacs mode for handling Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
KEYWORDS=~amd64 ~x86
LICENSE=Apache-2.0
PROPERTIES=live
RDEPEND=>=app-editors/emacs-23.1:*
SLOT=0
_eclasses_=elisp	17bb0076b1e93d2dba84995228871c99	elisp-common	a1054cff648e1c6a806e17001d052176	git-r3	86a0188f2ad9eb3d65e4d031ab8a0422
_md5_=360d1647a57d7040f899cbff3acaff39
