BDEPEND=>=app-editors/emacs-25.3:* >=dev-vcs/git-1.8.2.1[curl]
DEFINED_PHASES=compile configure info install postinst postrm prepare setup test unpack
DEPEND=app-emacs/s
DESCRIPTION=An emacs mode for handling Dockerfiles
EAPI=7
HOMEPAGE=https://github.com/spotify/dockerfile-mode
INHERIT=elisp git-r3
KEYWORDS=~amd64 ~x86
LICENSE=Apache-2.0
PROPERTIES=live
RDEPEND=>=app-editors/emacs-25.3:*
SLOT=0
_eclasses_=elisp-common	abb2dda42f680fce87602c8273f832c7	elisp	e7149f29f0c141396a0cec7cc59947a6	git-r3	875eb471682d3e1f18da124be97dcc81
_md5_=360d1647a57d7040f899cbff3acaff39
